#!/usr/bin/env bash
#Creating a script that uses nested if statements
file="school"
if [ -e $file ]
then
    echo "$file school file exists"

    if [ -s $file ]
    then
	echo "$file school file is not empty"
    else
	echo "$file school file is empty"
    fi

    if [ -f $file ]
    then
	echo "$file school is a regular file"
    fi
else
    echo "$file school file does not exist"
fi
