#!/usr/bin/env bash
#Creating a script that uses nested if statements
file="school"
if [ -e $file ]
then
    echo "$file file file exists"

    if [ -s $file ]
    then
	echo "$file file file is not empty"
    else
	echo "$file file file is empty"
    fi

    if [ -f $file ]
    then
	echo "$file file is a regular file"
    fi
else
    echo "$file file file does not exist"
fi
